### ISSUE TITLE
AttributeError: 'AsyncFunctionDef' object has no attribute 'statement'

### ISSUE THREAD

**Issue by orsinium** [usagitoneko97/klara#8]
Code:

```python
async def f():
    pass
```

Error:

```
❯ klara tmp.py
loaded extension: {'typeshed_stub.py', 'builtin_inference.py', '__init__.py', 'infer_z3.py', '99_math_z3.py'}

using configuration value: 
{   'config_file': None,
    'eq_neq': False,
    'input_test_file': 'tmp.py',
    'max_inference_value': None,
    'py_version': 3,
    'stubs': [],
    'type_inference': True,
    'typeshed_select': []}

Traceback (most recent call last):
  File "/home/gram/.local/bin/klara", line 8, in <module>
    sys.exit(main())
  File "/home/gram/.local/lib/python3.9/site-packages/klara/contract/__main__.py", line 50, in main
    output_test = run(input_file.read_text(), input_file.stem)
  File "/home/gram/.local/lib/python3.9/site-packages/klara/contract/__main__.py", line 36, in run
    cfg = MANAGER.build_cfg(tree)
  File "/home/gram/.local/lib/python3.9/site-packages/klara/klara_z3/cov_manager.py", line 64, in build_cfg
    c = cfg.Cfg(as_tree)
  File "/home/gram/.local/lib/python3.9/site-packages/klara/core/cfg.py", line 509, in __init__
    self.root, _, _ = self.parse(as_tree)
  File "/home/gram/.local/lib/python3.9/site-packages/klara/core/cfg.py", line 629, in parse
    head = self.build(basic_block, head, all_tail_list, func_tail_list)
  File "/home/gram/.local/lib/python3.9/site-packages/klara/core/cfg.py", line 535, in build
    tail_list, func_tail = meth(block)
  File "/home/gram/.local/lib/python3.9/site-packages/klara/core/cfg.py", line 589, in build_module
    head_returned, tail_list, _ = self.parse(self.as_tree.body)
  File "/home/gram/.local/lib/python3.9/site-packages/klara/core/cfg.py", line 627, in parse
    for basic_block in basic_block_parser.get_basic_block():
  File "/home/gram/.local/lib/python3.9/site-packages/klara/core/cfg.py", line 840, in get_basic_block
    basic_block_list = self.visit(node)
  File "/home/gram/.local/lib/python3.9/site-packages/klara/core/cfg.py", line 821, in visit
    return visitor(ast_node)
  File "/home/gram/.local/lib/python3.9/site-packages/klara/core/cfg.py", line 824, in generic_visit
    self._append_cache(ast_node.statement())
AttributeError: 'AsyncFunctionDef' object has no attribute 'statement'

```

**Comment by orsinium** [comment]
A similar one: `AttributeError: 'JoinedStr' object has no attribute 'statement'`

**Comment by oaustegard** [comment]
I received the same exact error when attempting to run against two different real-world python files. It worked fine however when ran against the exact test.py file from the README...

**Comment by usagitoneko97** [comment]
`JoinedStr` and `FormattedValue` is implemented [here](https://github.com/usagitoneko97/klara/commit/73677e98c8b2f29443cf022bb94904defdcf1f2f)

**Comment by usagitoneko97** [comment]
Implemented `JoinedStr` and `FormattedValue` [here](https://github.com/usagitoneko97/klara/commit/73677e98c8b2f29443cf022bb94904defdcf1f2f)
